# Generated by Django 4.2.7 on 2026-07-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_description_de_project_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_en',
        ),
    ]
